version: '3.4'
services:
  app:
    build:
      context: ./
      target: "${TARGET:-base}"
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "8080:80"
#      - '9003:9003'
#      - "10000:10000"
    volumes:
      - ./html:/var/www/html
    environment:
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123
      - AWS_DEFAULT_REGION=eu-west-1
      - AWS_BUCKET=avatars
      - AWS_EXTERNAL_URL=http://localhost:9000
      - AWS_URL=http://minio:9000
      - AWS_ENDPOINT=http://minio:9000
      - AWS_USE_PATH_STYLE_ENDPOINT=true
      - MINIO_VOLUMES=/minio-data
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
      - MINIO_SERVER_ACCESS_KEY=minio
      - MINIO_SERVER_SECRET_KEY=minio123
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_USERNAME=
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - REDIS_SESSION_DB=1
      - SESSION_DRIVER=redis
      - SESSION_CONNECTION=session
    depends_on:
      - node
      - minio
      - redis
      - db
      - maildev

  maildev:
    image: maildev/maildev:2.0.5
    ports:
      - "8025:1080"

  minio:
    image: minio/minio:RELEASE.2023-02-10T18-48-39Z
    command: server /data --console-address ":9001"
    ports: 
      - '9000:9000'
      - '9001:9001'
    volumes: 
      - ./storage:/data
    environment:
      - "MINIO_ROOT_USER=minio"
      - "MINIO_ROOT_PASSWORD=minio123"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  mc: # for cheking and test only
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minio minio123;
      /usr/bin/mc mb myminio/mybucket;
      /usr/bin/mc anonymous set public myminio/mybucket;
      "

  db:
    image: mariadb/server:10.5
    ports:
      - '3306:3306'
    environment:
      - MARIADB_ROOT_PASSWORD=
      - MARIADB_ALLOW_EMPTY_PASSWORD=true
      - MARIADB_INITDB_SKIP_TZINFO=true
      # MARIADB_ROOT_HOST : host for root user, defaults to '%'
      - MARIADB_DATABASE=laravel
      - MARIADB_USER=laravel
      - MARIADB_PASSWORD=laravel

  redis:
    image: redis:7.0.8-bullseye
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning 

  node:
    image: node:lts-alpine # lts-alpine3.17
    ports:
      - "5173:5173"
      - "8000:8000"
    volumes:
      - ./html:/html
    working_dir: /html
    command: sh -c "npm install && npm run dev"
  
