version: '2'
services:
  maildev:
    image: maildev/maildev
    ports:
      - "8025:1080"
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
  db:
    image: mariadb/server:10.5        
    ports:
      - '3306:3306'
    environment:
      - MARIADB_ROOT_PASSWORD=
      - MARIADB_ALLOW_EMPTY_PASSWORD=true
      - MARIADB_INITDB_SKIP_TZINFO=true
      # MARIADB_ROOT_HOST : host for root user, defaults to '%'
      - MARIADB_DATABASE=laravel
      - MARIADB_USER=laravel
      - MARIADB_PASSWORD=laravel
  redis:
    image: redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning    
  app:    
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile    
    ports:
      - "8080:80"
      - "8000:8000"
      - "9090:9000"
    volumes:
      - ./Laravel:/var/www/Laravel  
      - ./html:/var/www/html
    environment:
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_DEFAULT_REGION=eu-west-1
      - AWS_BUCKET=avatars
      - AWS_URL=http://127.0.0.1:9000
      - AWS_ENDPOINT=http://127.0.0.1:9000
      - AWS_USE_PATH_STYLE_ENDPOINT=false
      - MINIO_VOLUMES=/minio-data
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_SERVER_ACCESS_KEY=minioadmin
      - MINIO_SERVER_SECRET_KEY=minioadmin
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    depends_on:
      - minio
      - redis
      - db
      - maildev
  
  minio-client:  # service not necessary, used here to explain how to interact from the container with Minio
    image: minio/mc
    depends_on:
      - minio
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin) do echo '...waiting...' && sleep 3; done;
      /usr/bin/mc mb myminio/test-bucket;
      echo 'my content' > myfile.txt;
      /usr/bin/mc cp myfile.txt myminio/test-bucket;
      echo 'copied';
      sleep 9999;
      "
    # /usr/bin/mc config host add myminio http://app:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
